.PHONY: all clean

CFLAGS+=
LDFLAGS+=-lm -O3 -std=c++11     # link to math library

TARGET=train test

all: $(TARGET)
# type make/make all to compile test_hmm

clean:
	$(RM) $(TARGET)   # type make clean to remove the compiled file
